openapi: '3.0.2'
info:
  title: onboarding-open-api
  version: '3.1'
servers:
  - url: http://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      operationId: onboarding-operation-id
      responses:
        200:
          description: 'OK'
